import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { documentService } from '../../services/documentService';
import { useAuth } from '../../hooks/useAuth';
import { useToast } from '../../contexts/ToastContext';
import CommentsSection from '../../components/user/CommentsSection';
import DocumentRecommendations from '../../components/user/DocumentRecommendations';
import CreateVersionModal from '../../components/user/CreateVersionModal';
import Button from '../../components/common/Button';
import Badge from '../../components/common/Badge';
import LoadingSpinner from '../../components/common/LoadingSpinner';
import Card from '../../components/common/Card';
import { useViewHistory } from '../../hooks/useViewHistory';

const LANGUAGES = [
  { key: 'translatedContentFr', label: 'French', flag: '🇫🇷', dir: 'ltr' },
  { key: 'translatedContentAr', label: 'Arabic',  flag: '🇸🇦', dir: 'rtl' },
  { key: 'translatedContentEs', label: 'Spanish', flag: '🇪🇸', dir: 'ltr' },
];

const AITranslationsCard = ({ document }) => {
  const [activeTab, setActiveTab] = useState(
    LANGUAGES.find(l => document[l.key])?.key ?? null
  );
  const active = LANGUAGES.find(l => l.key === activeTab);

  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
      {/* Header */}
      <div className="flex items-center gap-3 px-5 py-4 border-b border-gray-100 bg-gradient-to-r from-purple-50 to-indigo-50">
        <div className="w-8 h-8 bg-gradient-to-br from-purple-500 to-indigo-600 rounded-lg flex items-center justify-center text-sm">
          🤖
        </div>
        <div>
          <h3 className="text-sm font-bold text-gray-900">AI Translations</h3>
          <p className="text-xs text-gray-500">Generated by Gemini via Kafka pipeline</p>
        </div>
        <span className="ml-auto text-xs font-medium bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full">
          Powered by Gemini
        </span>
      </div>

      {/* Tab bar */}
      <div className="flex border-b border-gray-100">
        {LANGUAGES.filter(l => document[l.key]).map(l => (
          <button
            key={l.key}
            onClick={() => setActiveTab(l.key)}
            className={`flex items-center gap-1.5 px-5 py-2.5 text-sm font-medium transition-colors border-b-2 -mb-px ${
              activeTab === l.key
                ? 'border-indigo-600 text-indigo-700'
                : 'border-transparent text-gray-500 hover:text-gray-800 hover:border-gray-300'
            }`}
          >
            <span>{l.flag}</span> {l.label}
          </button>
        ))}
      </div>

      {/* Content */}
      {active && (
        <div className="px-5 py-4">
          <p
            dir={active.dir}
            className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap"
          >
            {document[active.key]}
          </p>
        </div>
      )}
    </div>
  );
};

const DocumentDetailPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const { showSuccess, showError } = useToast();
  const { addToHistory } = useViewHistory(user?.id);

  const [document, setDocument] = useState(null);
  const [categories, setCategories] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isVersionModalOpen, setIsVersionModalOpen] = useState(false);

  const fetchDocumentData = async () => {
    try {
      setIsLoading(true);
      const [docData, cats, depts] = await Promise.all([
        documentService.getDocumentById(id),
        documentService.getCategories(),
        documentService.getDepartments()
      ]);
      setDocument(docData);
      setCategories(cats);
      setDepartments(depts);
      
      // Fire and forget view increment
      documentService.incrementViewCount(id);
    } catch (error) {
      showError('Failed to load document details');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchDocumentData();
    addToHistory(id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  const handleDownload = () => {
    if (!document?.fileUrl) {
      showError('No file available for this document');
      return;
    }
    // Pre-signed URLs embed the hostname in their signature — rewriting the host breaks them.
    // The bucket has anonymous download access, so extract the key and use a direct URL instead.
    const match = document.fileUrl.match(/\/dms-bucket\/([^?]+)/);
    if (!match) {
      showError('Invalid file URL');
      return;
    }
    const url = `http://localhost:9000/dms-bucket/${match[1]}`;
    const a = window.document.createElement('a');
    a.href = url;
    a.download = document.title || 'document';
    a.target = '_blank';
    a.rel = 'noopener noreferrer';
    a.click();
    documentService.incrementDownloadCount(id);
    showSuccess('Download started');
  };

  const handleRestoreVersion = async (versionNumber) => {
    if (window.confirm(`Are you sure you want to restore version ${versionNumber}? This will create a new version.`)) {
      try {
        await documentService.restoreDocumentVersion(id, versionNumber);
        showSuccess(`Restored from version ${versionNumber}`);
        fetchDocumentData();
      } catch (err) {
        showError('Failed to restore version');
      }
    }
  };

  if (isLoading) {
    return <div className="py-20"><LoadingSpinner size="lg" /></div>;
  }

  if (!document) {
    return (
      <div className="text-center py-20">
        <h2 className="text-2xl font-bold text-gray-800">Document Not Found</h2>
        <Button className="mt-4" onClick={() => navigate('/documents')}>Back to Library</Button>
      </div>
    );
  }

  const category = categories.find(c => c.id === document.categoryId);
  const department = departments.find(d => d.id === document.departmentId);
  const isAdminOrOwner = user?.role === 'admin' || user?.id === document.uploadedBy;

  // Render Preview based on type
  const renderPreview = () => {
    const type = document.fileType?.toUpperCase();
    if (['JPG', 'JPEG', 'PNG', 'GIF'].includes(type)) {
      return (
        <div className="w-full h-96 bg-gray-100 rounded-lg flex items-center justify-center overflow-hidden border border-gray-200">
          <img src={`https://via.placeholder.com/800x600.png?text=${document.title}`} alt={document.title} className="object-contain max-h-full" />
        </div>
      );
    }
    return (
      <div className="w-full h-64 bg-gray-100 rounded-lg flex flex-col items-center justify-center border border-gray-200 text-gray-500">
        <div className="text-6xl mb-4">📄</div>
        <p className="font-medium">Preview not available for {type} files.</p>
        <Button variant="secondary" className="mt-4" onClick={handleDownload}>Download to View</Button>
      </div>
    );
  };

  return (
    <div className="max-w-7xl mx-auto pb-12">
      {/* SECTION 1: HEADER */}
      <div className="mb-6">
        <button onClick={() => navigate(-1)} className="text-blue-600 hover:underline flex items-center text-sm font-medium mb-4">
          ← Back to Documents
        </button>
        
        <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <h1 className="text-3xl font-bold text-gray-900 leading-tight">{document.title}</h1>
              <Badge variant={document.status === 'published' ? 'success' : 'warning'}>
                {document.status?.toUpperCase() || 'DRAFT'}
              </Badge>
            </div>
            <p className="text-sm text-gray-500">
              Version {document.currentVersion} • Last updated {new Date(document.updatedAt).toLocaleDateString()}
            </p>
          </div>

          <div className="flex flex-wrap gap-2">
            <Button variant="primary" onClick={handleDownload}>
              Download
            </Button>
            <Button variant="secondary" onClick={() => alert('Share feature coming soon!')}>
              Share
            </Button>
            {isAdminOrOwner && (
              <>
                <Button variant="ghost" onClick={() => setIsVersionModalOpen(true)}>
                  + New Version
                </Button>
                <Button variant="ghost" className="text-red-600 hover:text-red-700 hover:bg-red-50">
                  Delete
                </Button>
              </>
            )}
          </div>
        </div>
      </div>

      {/* SECTION 2: CONTENT AREA */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* LEFT COLUMN: Preview, Metadata & Comments */}
        <div className="lg:col-span-2 space-y-6">
          {renderPreview()}

          <Card title="Document Metadata">
            {document.fileUrl && (
                <div className="mb-4">
                    <a href={document.fileUrl} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline inline-flex items-center gap-1 font-medium">
                        🔗 Open Original File
                    </a>
                </div>
            )}
            <div className="prose max-w-none text-gray-700 mb-6 whitespace-pre-wrap text-sm">
              {document.description || 'No description provided.'}
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 py-4 border-t border-b border-gray-100 mb-6">
              <div>
                <p className="text-xs text-gray-500 font-medium uppercase tracking-wider mb-1">Category</p>
                <p className="text-sm font-medium">{category?.icon} {category?.name}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 font-medium uppercase tracking-wider mb-1">Department</p>
                <p className="text-sm font-medium">{department?.name || 'Global'}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 font-medium uppercase tracking-wider mb-1">File Type</p>
                <p className="text-sm font-medium uppercase">{document.fileType}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 font-medium uppercase tracking-wider mb-1">File Size</p>
                <p className="text-sm font-medium">{(document.fileSize / 1024 / 1024).toFixed(2)} MB</p>
              </div>
            </div>

            {document.tags && document.tags.length > 0 && (
              <div>
                <p className="text-xs text-gray-500 font-medium uppercase tracking-wider mb-2">Tags</p>
                <div className="flex flex-wrap gap-2">
                  {document.tags.map(tag => (
                    <span key={tag} className="px-2.5 py-1 rounded-md bg-gray-100 text-gray-700 text-xs font-medium cursor-pointer hover:bg-gray-200 transition-colors">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </Card>

          {/* AI Translations */}
          {(document.translatedContentFr || document.translatedContentAr || document.translatedContentEs) && (
            <AITranslationsCard document={document} />
          )}

          {/* Comments Section */}
          <CommentsSection documentId={document.id} />

          {/* Recommendations */}
          <DocumentRecommendations
            currentDocument={document}
            categories={categories}
          />
        </div>

        {/* RIGHT COLUMN: Sidebar (Stats & Versions) */}
        <div className="space-y-6">
          
          <Card title="Quick Stats">
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-gray-50 p-4 rounded-lg text-center">
                <span className="block text-2xl font-bold text-gray-900">{document.viewCount || 0}</span>
                <span className="text-xs text-gray-500 font-medium uppercase">Views</span>
              </div>
              <div className="bg-gray-50 p-4 rounded-lg text-center">
                <span className="block text-2xl font-bold text-gray-900">{document.downloadCount || 0}</span>
                <span className="text-xs text-gray-500 font-medium uppercase">Downloads</span>
              </div>
            </div>
          </Card>

          <Card title="Version History" className="sticky top-6">
            <div className="space-y-0">
              {[...(document.versions || [])].sort((a, b) => b.versionNumber - a.versionNumber).map((ver, idx) => (
                <div key={ver.versionNumber} className={`relative pl-6 py-4 ${idx !== document.versions.length - 1 ? 'border-b border-gray-100' : ''}`}>
                  {/* Timeline dot */}
                  <div className={`absolute left-0 top-6 w-2.5 h-2.5 rounded-full ${ver.versionNumber === document.currentVersion ? 'bg-blue-600 ring-4 ring-blue-100' : 'bg-gray-300'}`}></div>
                  
                  <div className="flex justify-between items-start mb-1">
                    <h4 className="font-semibold text-gray-900 text-sm flex items-center gap-2">
                      v{ver.versionNumber}
                      {ver.versionNumber === document.currentVersion && <Badge variant="info">Current</Badge>}
                    </h4>
                    <span className="text-xs text-gray-500">{new Date(ver.uploadedAt).toLocaleDateString()}</span>
                  </div>
                  
                  <p className="text-sm text-gray-600 mb-3">{ver.notes}</p>
                  
                  <div className="flex gap-3 text-xs">
                    <button className="text-blue-600 hover:underline font-medium" onClick={handleDownload}>Download</button>
                    {isAdminOrOwner && ver.versionNumber !== document.currentVersion && (
                      <button 
                        className="text-gray-500 hover:text-gray-900 font-medium"
                        onClick={() => handleRestoreVersion(ver.versionNumber)}
                      >
                        Restore
                      </button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </Card>
        </div>

      </div>

      <CreateVersionModal 
        isOpen={isVersionModalOpen}
        onClose={() => setIsVersionModalOpen(false)}
        document={document}
        onSuccess={fetchDocumentData}
      />
    </div>
  );
};

export default DocumentDetailPage;
